vscode:
  extensions:
    - ms-vscode-remote.remote-ssh-edit@0.47.2:PLSDDtiOKZvFLSckoDi1ig==
    - Swellaby.node-pack@0.1.10:GbHaYA+HsRT1AQXX4N6fbw==
    - rahulsahay.Csharp-ASPNETCore@1.11.0:w2FCMVlXLmqKzfNYGrYRFQ==
    - temilaj.asp-net-core-vs-code-extension-pack@1.0.3:VdufhVzUKQKra2K0rqTJtw==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - pasalog.a-frame-for-vscode@1.2.5:gfBlFvNa1wizu0ASLK7oLg==
    - fireside21.cshtml@0.1.3:ljQzC9xtdIrvck13SCEffA==
    - ms-vscode.csharp@1.21.5:L1UR0rKjGSDRA3zUSyHwZQ==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - jasonnutter.search-node-modules@1.3.0:G786iJxLfc//erh6tQ8MWw==
    - VisualStudioExptTeam.vscodeintellicode@1.2.0:ZVy7XFOZUd4m0FZb3PUFbA==
    - eg2.vscode-npm-script@0.3.9:FTjGx1Gmz+E5EP1FHaYLqQ==
    - jchannon.csharpextensions@1.3.0:/qyq0PYiY/Kc287KLF4X6w==
    - k--kato.docomment@0.1.8:CNPkp66CComHdjDCWNbiQA==
    - ms-vscode.azure-account@0.8.7:9b7Ez1SoEMxNn23S/01OYw==
    - ms-vscode-remote.remote-ssh@0.47.2:cfQ6wdb+JDVXFE6c5KWPeQ==
    - eamodio.gitlens@10.1.1:W/mM/phTCRJ9XghzvZRI4g==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - pflannery.vscode-versionlens@0.24.0:FzMGwBqMxkIHqADhVK2e2Q==
    - ms-mssql.mssql@1.7.0:OtBZSZx5k+UXsGKzNKsLtg==
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==